### PR TITLE
Introduce GraalVM JDK 23

### PR DESCRIPTION
**Pull request by brahimhaddou**

### CODE REVIEW

**Comment by fniephaus** [comment]
Thanks for the PR! Could you please add `23` to the build matrix so that this is tested?

https://github.com/graalvm/homebrew-tap/blob/d8d12ef8ee6462a608a8165ed25c88444238708a/.github/workflows/main.yml#L11

**Comment by ezzarghili** [comment]
> Thanks for the PR! Could you please add `23` to the build matrix so that this is tested?
> 
> https://github.com/graalvm/homebrew-tap/blob/d8d12ef8ee6462a608a8165ed25c88444238708a/.github/workflows/main.yml#L11

@fniephaus maybe remove EOL version there ? 20 and 22

**Review by ezzarghili — APPROVED** [review]
LGTM

**Comment by fniephaus** [comment]
> maybe remove EOL versions there ? 20 and 22

I would've kept them, you can still install them.

**Review by fniephaus — DISMISSED** [review]
LGTM

**Comment by ezzarghili** [comment]
> > maybe remove EOL versions there ? 20 and 22
> 
> I would've kept them, you can still install them.

We are not removing them.they are not supported and will not get update, I think running tests on them is not necessary and wasteful of CI resources

**Comment by fniephaus** [comment]
> I think running tests on them is not necessary and wasteful of CI resources

Good point, I agree.

**Review by fniephaus — APPROVED** [review]

**Pull request merged**
